#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#000000} 
    wm focusmodel $top passive
    wm geometry $top 624x181+482+209
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Seven Cipher"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    entry $top.ent38 \
        -background {#595959} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#ffffff} -highlightcolor {#ffffff} \
        -insertbackground {#ffffff} -textvariable DataPath -width 444 
    vTcl:DefineAlias "$top.ent38" "Entry_DataPath" vTcl:WidgetProc "Toplevel1" 1
    entry $top.cpd39 \
        -background {#595959} -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor {#ffffff} -insertbackground {#ffffff} \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable keyPath -width 444 
    vTcl:DefineAlias "$top.cpd39" "Entry_KeyPath" vTcl:WidgetProc "Toplevel1" 1
    button $top.but40 \
        -activebackground {#000000} -activeforeground {#000000} \
        -background {#000000} -command LoadDataPath \
        -disabledforeground {#a3a3a3} -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Data Path} 
    vTcl:DefineAlias "$top.but40" "Button_DataPath" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex47 \
        -background {#595959} -font TkTextFont -foreground {#ffffff} \
        -height 64 -highlightbackground {#d9d9d9} -highlightcolor {#ffffff} \
        -insertbackground {#ffffff} -selectbackground {#c4c4c4} \
        -selectforeground black -width 494 -wrap word 
    .top37.tex47 configure -font TkTextFont
    .top37.tex47 insert end text
    vTcl:DefineAlias "$top.tex47" "Text_Data" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tex47 <FocusIn> {
        lambda e: UpdateDataText(e)
    }
    button $top.cpd48 \
        -activebackground {#000000} -activeforeground {#000000} \
        -background {#000000} -command DecryptData \
        -disabledforeground {#a3a3a3} -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Decrypt 
    vTcl:DefineAlias "$top.cpd48" "Button_Decrypt" vTcl:WidgetProc "Toplevel1" 1
    button $top.cpd49 \
        -activebackground {#000000} -activeforeground {#000000} \
        -background {#000000} -command EncryptData \
        -disabledforeground {#a3a3a3} -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Encrypt 
    vTcl:DefineAlias "$top.cpd49" "Button_Encrypt" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground {#595959} -activeforeground {#ffffff} \
        -background {#000000} -disabledforeground {#a3a3a3} \
        -foreground {#ffffff} -text KEY 
    vTcl:DefineAlias "$top.lab50" "Label_Key" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd51 \
        -activebackground {#595959} -activeforeground {#ffffff} \
        -background {#000000} -disabledforeground {#a3a3a3} \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text DATA 
    vTcl:DefineAlias "$top.cpd51" "Label_Data" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent38 \
        -in $top -x 62 -y 56 -width 444 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd39 \
        -in $top -x 61 -y 21 -width 444 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 517 -y 54 -width 97 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex47 \
        -in $top -x 10 -y 90 -width 494 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd48 \
        -in $top -x 517 -y 90 -width 97 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.cpd49 \
        -in $top -x 518 -y 120 -width 97 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab50 \
        -in $top -x 10 -y 20 -width 36 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd51 \
        -in $top -x 12 -y 55 -width 46 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

